server:
  name: go-message
  port: 8080

log:
  level: debug
  field_map:
    time: "@timestamp"
    msg: message

mongo:
  uri: mongodb://@localhost:27017
  database: master_data

amq:
  addr: dummy-addr
  host: dummy-host
  username: username
  password: password
  destination_name: dummy-destination
  subscription_name: dummy-subscription

batch_worker:
  batch_size: 1000
  timeout: 10
  limit_retry: 3
